### ISSUE TITLE
Bug of input in example/PageRankVertex.cc

### ISSUE THREAD

**Issue by kuwii** [schencoding/GraphLite#8]
For example, if I have a graph like this:
```
7
8
0 1
0 2
1 2
3 1
3 2
4 5
4 6
5 6
```
It will be divided into 4 part as default. So the input for the third worker will be:
```
2
0
```
So there will be no edge in this input, and this will be invalid input of the program according to the code in loadGraph() function. But obviously it should not be invalid input because it is possible to have a graph like this. When I run the program, it will show me "Sender: connect: Connection refused".

**Comment by ghost** [comment]
Sorry, I don't know what your problem is. Could you please show me your log in `WorkerOut`. Or you can use `dmesg | grep graphlite` to find out why graphlite was killed.

**Comment by niusj** [comment]
The bug is fixed now after we checked. "if (m_total_edge <= 0) return;" has been added at the first line of loadGraph() in PageRankVertex.cc. Please see the newest version. Thanks for the bug report : )

**Comment by kuwii** [comment]
@zhoudongyan 
This problem is in `example/PageRankVertex.cc`, I'll explain it with an example:
The graph I use is:
```
7
8
0 1
0 2
1 2
3 1
3 2
4 5
4 6
5 6
```
Then,  run bin hash-partitioner.pl, it will divide the input into 4 parts. And the third part will be:
```
2
0
```
Now, as you can see, there is no edge in the input file. But your code in `example/PageRankVertex.cc` is (line 76~82):
```
        const char *line= getEdgeLine();

        // Note: modify this if an edge weight is to be read
        //       modify the 'weight' variable

        sscanf(line, "%lld %lld", &from, &to);
        addEdge(from, to, &weight);
```
So you did not consider the case of no edge in input. The program can not work correctly in the case of my example.

**Comment by kuwii** [comment]
@niusj  OK, thanks : )
